version: '1'
services:
  app:
    build: .
    container_name: nest_ebook
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - .:/data
    ports:
      - '6379:6379'

volumes:
  pgdata: {}
